In [1]:
from scipy import linalg
import numpy as np

a. Define a matrix A

In [9]:
A = np.arange(1,10).reshape(3,3)
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


b. Define a vector b

In [5]:
b = np.arange(1,4)
print(b)

[1 2 3]


c. Solve the linear system of equations A x = b

In [8]:
x = linalg.solve(A,b)

C:\Users\clasp553\AppData\Local\Temp/ipykernel_1416/4038079409.py:1: LinAlgWarning: Ill-conditioned matrix (rcond=2.20282e-18): result may not be accurate.
  x = linalg.solve(A,b)


d. Check that your solution is correct by plugging it into the equation

In [16]:
solution = np.dot(A,x)
print(solution)

[1. 2. 3.]


e. Repeat steps a-d using a random 3x3 matrix B (instead of the vector b)

In [27]:
B = np.random.randint(1,10, size=(3,3))
print(B)
y = linalg.solve(A,B) #A y = B
solution = np.dot(A,y)
print(solution)

[[3 5 9]
 [7 2 7]
 [5 3 5]]
[[8. 0. 9.]
 [0. 0. 7.]
 [0. 0. 5.]]


C:\Users\clasp553\AppData\Local\Temp/ipykernel_1416/3277139369.py:3: LinAlgWarning: Ill-conditioned matrix (rcond=2.20282e-18): result may not be accurate.
  y = linalg.solve(A,B) #A y = B


f. Solve the eigenvalue problem for the matrix A and print the eigenvalues and eigenvectors

In [29]:
evals, evecs = linalg.eig(A)
print(evals, evecs)

[ 1.61168440e+01+0.j -1.11684397e+00+0.j -3.38433605e-16+0.j] [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


g. Calculate the inverse, determinant of A

In [30]:
Ainv = linalg.inv(A)
print(Ainv)
Ainv_det = linalg.det(Ainv)
print(Ainv_det)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
0.024499999999999914


h. Calculate the norm of A with different orders

In [31]:
i = -2
while i < 3:
    if i == 0:
        i+=1
    else:
        print("Order " + str(i) + " matrix A norm:")
        print(linalg.norm(A,i))
        i+=1

Order -2 matrix A norm:
1.4026654043257372e-16
Order -1 matrix A norm:
12.0
Order 1 matrix A norm:
18.0
Order 2 matrix A norm:
16.84810335261421
